name: first_work_flow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: run maven
        run: mvn clean install 
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_project
          path: ./target/demo-0.0.1-SNAPSHOT.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get artfact
        uses: actions/download-artifact@v4
        with:
          name: test_project
      - name: output context
        run: ls
