name: first_work_flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@4
      - name: print goodbye
        run: echo "good bye "
